name: Unit Test
on: push

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y
      - run: sudo apt install cargo
      - run: cargo install stable
      - run: cargo test
