name: Unit Test
on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    name: Unit Test
    steps:
      - uses: actions/checkout@v3
      - run: cargo test
