name: Unit Test
on: push

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apt update -y
      - run: apt install cargo
      - run: cargo install stable
      - run: cargo test
